apiVersion: v1
kind: Service
metadata:
  name: {{ include "bonusblock-faucet.fullname" . }}
  labels:
    {{- include "bonusblock-faucet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    {{- include "bonusblock-faucet.selectorLabels" . | nindent 4 }}